[workspace]
members = [
    "compiler/common",
    "compiler/chili_span",
    "compiler/chili_error",
    "compiler/chili_ast",
    "compiler/chili_token",
    "compiler/chili_parse",
    "compiler/chili_astgen",
    "compiler/chili_resolve",
    # "compiler/chili_infer",
    "compiler/chili_infer_new",
    # "compiler/chili_check",
    # "compiler/chili_lint",
    # "compiler/chili_llvm",
    "compiler/chili_main",
]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
