[workspace]
members = [
    "compiler/common",
    "compiler/chili_span",
    "compiler/chili_error",
    "compiler/chili_ty",
    "compiler/chili_ast",
    "compiler/chili_pass",
    "compiler/chili_token",
    "compiler/chili_parse",
    "compiler/chili_check",
    "compiler/chili_typeck",
    "compiler/chili_llvm",
    "compiler/chili_main",
]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
