[workspace]
members = [
    "compiler/common",
    "compiler/chilic_span",
    "compiler/chilic_error",
    "compiler/chilic_ty",
    "compiler/chilic_ast",
    "compiler/chilic_pass",
    "compiler/chilic_token",
    "compiler/chilic_parse",
    "compiler/chilic_check",
    "compiler/chilic_infer",
    "compiler/chilic_llvm",
    "compiler/chilic_main",
]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
