[package]
name = "chili_workspace"
version = "0.0.1"
edition = "2021"

[dependencies]
codespan = "0.11.1"
codespan-reporting = "0.11.1"

common = { path = '../common' }
chili_ty = { path = '../chili_ty' }
chili_ast = { path = "../chili_ast" }
