[package]
name = "chilic_ty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ustr = "0.8.1"

common = { path = "../common" }
chilic_span = { path = "../chilic_span" }
