[package]
name = "chili_token"
version = "0.1.0"
edition = "2021"

[dependencies]
ustr = "0.8.1"
strum_macros = "0.23.1"
unicode-xid = "0.2.2"

chili_span = { path = "../chili_span" }
chili_error = { path = "../chili_error" }
