[package]
name = "chili_vm"
version = "0.1.0"
edition = "2021"

[dependencies]
# colored = "2.0.0"
# strum_macros = "0.23.1"
# region = "3.0.0"
# libffi = "2.0.0"
# libloading = "0.7.1"
# ustr = "0.8.1"

# chili_parse = { path = "../chili_parse" }
# common = { path = "../common" }
