[package]
name = "chili_defer"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
chili_span = { path = "../chili_span" }
chili_error = { path = "../chili_error" }
chili_ast = { path = "../chili_ast" }
